---
- name: Clone cloudflare zlib repo
  git:
    repo: https://github.com/cloudflare/zlib.git
    dest: "{{ src_location }}/zlib"
    force: yes
    version: af9ef2e94cb9ffebc8dc6cc6d856e494880d869b

- name: Zlib distclean
  make:
    file: Makefile.in
    target: distclean
    chdir: "{{ src_location }}/zlib"

- name: Set zlib nginx compile args
  set_fact:
    nginx_configure_arg: "{{ nginx_configure_arg }} --with-zlib={{ src_location }}/zlib"
