---
- name: Remove nginx dir if exsits
  file:
    path: "{{ src_location }}/nginx-{{ nginx_version }}"
    state: absent

- name: Set nginx install prefix
  set_fact:
    nginx_configure_arg: "{{ nginx_configure_arg }} --prefix={{ nginx_install }}"

- name: Download nginx src tarball
  get_url:
    url: "http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
    dest: "{{ src_location }}/nginx-{{ nginx_version }}.tar.gz"

- name: Download nginx gpg asc
  get_url:
    url: "http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz.asc"
    dest: "{{ src_location }}/nginx-{{ nginx_version }}.tar.gz.asc"

# BTW, ansible is no gpg verify module
- name: Import nginx gpg key # noqa 305 301
  command: gpg --keyserver {{ item }} --recv-key 520A9993A1C052F8
  register: nginx_gpg_verify
  loop:
    - hkp://keyserver.ubuntu.com:80
    - ha.pool.sks-keyservers.net
    - hkp://p80.pool.sks-keyservers.net:80
    - pgp.mit.edu
  when: nginx_gpg_verify is not defined or nginx_gpg_verify is failure
  failed_when: nginx_gpg_verify is failure

- name: Verify nginx tarball # noqa 305 301
  shell:
    cmd: gpg --trusted-key 520A9993A1C052F8 --verify
      nginx-{{ nginx_version }}.tar.gz.asc
      nginx-{{ nginx_version }}.tar.gz
    chdir: "{{ src_location }}"

- name: Extract nginx src tarball
  unarchive:
    src: "{{ src_location }}/nginx-{{ nginx_version }}.tar.gz"
    dest: "{{ src_location }}"
    remote_src: yes

- name: Remove nginx src tarball
  file:
    path: "{{ src_location }}/nginx-{{ nginx_version }}.tar.gz"
    state: absent

- name: Remove nginx gpg asc
  file:
    path: "{{ src_location }}/nginx-{{ nginx_version }}.tar.gz.asc"
    state: absent

- name: Get kn007 nginx.patch
  get_url:
    url: https://raw.githubusercontent.com/kn007/patch/master/nginx.patch
    dest: "{{ src_location }}/nginx-{{ nginx_version }}/nginx.patch"

- name: Patch nginx
  patch:
    src: "{{ src_location }}/nginx-{{ nginx_version }}/nginx.patch"
    basedir: "{{ src_location }}/nginx-{{ nginx_version }}"
    strip: 1
    remote_src: yes

- name: Configure nginx # noqa 305 301
  shell:
    cmd: "./configure {{ nginx_configure_arg }}"
    chdir: "{{ src_location }}/nginx-{{ nginx_version }}"
  environment:
    LUAJIT_LIB: "{{ lua_jit_install }}/lib"
    LUAJIT_INC: "{{ lua_jit_install }}/include/luajit-2.1"

- name: Make nginx
  make:
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus }}"
    chdir: "{{ src_location }}/nginx-{{ nginx_version }}"

- name: Install nginx
  make:
    target: install
    chdir: "{{ src_location }}/nginx-{{ nginx_version }}"

- name: Create nginx log dir
  file:
    path: /var/log/nginx/
    state: directory

- name: Link nginx bin to /usr/bin
  file:
    src: "{{ nginx_install }}/sbin/nginx"
    dest: "/usr/bin/nginx"
    state: link

- name: Install nginx service
  template:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service
    mode: 0755
  notify: start nginx
